# Generated by Django 5.1.6 on 2025-03-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethnicapp', '0003_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='status',
            field=models.CharField(default='Available', max_length=40),
        ),
    ]
