# Generated by Django 5.1.1 on 2025-03-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethnicapp', '0004_stay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
