# Generated by Django 5.1.1 on 2025-03-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethnicapp', '0005_stay_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total', models.IntegerField()),
                ('status', models.CharField(max_length=30, null=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethnicapp.stay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethnicapp.customer')),
            ],
        ),
    ]
